version: '3'
services:
    mysite-nginx-load-balancer:
        build:
            context: nginx-load-balancer
            dockerfile: Dockerfile
        image: otus/mysite-nginx-load-balancer
        container_name: mysite-nginx-load-balancer
        volumes:
            - ../app:/app:delegated
            - ../sock:/sock
        depends_on:
            - mysite-nginx-1
            - mysite-nginx-2
            - mysite-nginx-3
        ports:
            - "80:80"
        networks:
            - mysite-network

    mysite-nginx-1:
        build:
            context: nginx-1
            dockerfile: Dockerfile
        image: otus/mysite-nginx-1
        container_name: mysite-nginx-1
        volumes:
            - ../app:/app:delegated
            - ../sock:/sock
        depends_on:
            - mysite-php-fpm-1
            - mysite-php-fpm-2
            - mysite-php-fpm-3
        networks:
            - mysite-network

    mysite-nginx-2:
        build:
            context: nginx-2
            dockerfile: Dockerfile
        image: otus/mysite-nginx-2
        container_name: mysite-nginx-2
        volumes:
            - ../app:/app:delegated
            - ../sock:/sock
        depends_on:
            - mysite-php-fpm-1
            - mysite-php-fpm-2
            - mysite-php-fpm-3
        networks:
            - mysite-network

    mysite-nginx-3:
        build:
            context: nginx-3
            dockerfile: Dockerfile
        image: otus/mysite-nginx-3
        container_name: mysite-nginx-3
        volumes:
            - ../app:/app:delegated
            - ../sock:/sock
        depends_on:
            - mysite-php-fpm-1
            - mysite-php-fpm-2
            - mysite-php-fpm-3
        networks:
            - mysite-network

    mysite-php-fpm-1:
        build:
            context: php-fpm-1
            dockerfile: Dockerfile
        image: otus/mysite-php-fpm-1
        container_name: mysite-php-fpm-1
        volumes:
            - ../app:/app:delegated
            - ../sock:/sock
        depends_on:
            - mcrouter
        networks:
            - mysite-network

    mysite-php-fpm-2:
        build:
            context: php-fpm-2
            dockerfile: Dockerfile
        image: otus/mysite-php-fpm-2
        container_name: mysite-php-fpm-2
        volumes:
            - ../app:/app:delegated
            - ../sock:/sock
        depends_on:
            - mcrouter
        networks:
            - mysite-network

    mysite-php-fpm-3:
        build:
            context: php-fpm-3
            dockerfile: Dockerfile
        image: otus/mysite-php-fpm-3
        container_name: mysite-php-fpm-3
        volumes:
            - ../app:/app:delegated
            - ../sock:/sock
        depends_on:
            - mcrouter
        networks:
            - mysite-network

    mysite-memcached-1:
        image: memcached:latest
        container_name: mysite-memcached-1
        ports:
            - "11212:11211"
        networks:
            - mysite-network

    mysite-memcached-2:
        image: memcached:latest
        container_name: mysite-memcached-2
        ports:
            - "11213:11211"
        networks:
            - mysite-network

    mysite-memcached-3:
        image: memcached:latest
        container_name: mysite-memcached-3
        ports:
            - "11214:11211"
        networks:
            - mysite-network

    mcrouter:
        build:
            context: mcrouter
            dockerfile: Dockerfile
        image: otus/mysite-mcrouter
        links:
            - mysite-memcached-1:memcached1
            - mysite-memcached-2:memcached2
            - mysite-memcached-3:memcached3
        command: mcrouter -f /etc/mcrouter/config.json -p 11211
        depends_on:
            - mysite-memcached-1
            - mysite-memcached-2
            - mysite-memcached-3
        ports:
            - 11211:11211
        networks:
            - mysite-network

    php-cli:
        build:
            context: php-cli
            dockerfile: Dockerfile
        image: otus/php-cli
        container_name: otus-php-cli
        volumes:
            - ../app:/app:delegated

networks:
    mysite-network:
        driver: bridge